### ISSUE TITLE
error in running DataPreprocessing.ipynb

### ISSUE THREAD

**Issue by KH-RES** [krzysiekniburski/Network-Traffic-Classification#1]
hello **krzysiekniburski**,
When running the **DataPreprocessing.ipynb**, and more precisely, arriving at the code fragment:
```
feats = [x for x in df.columns if x != 'ProtocolName'] 
X = df[feats].astype(float) 
Y = df['ProtocolName']
```
it gave me this error : 
**#error : could not convert string to float : '172.19.1.46-10.200.7.7-52422-3128-6'**

please any help.
thank's in advance.

**Comment by krzysiekniburski** [comment]
Hello, 
Feature can only be numeric values. IP address is object type so it should be converted into numeric value. It can be done using function in the beginning of the file:
Function that changes IP addresses into numbers
def ip2int(ip):
    packedIP = socket.inet_aton(ip)
    return struct.unpack("!L", packedIP)[0]

Converting IP addresses into numbers
df['Source.IP'] = df['Source.IP'].apply(ip2int)
df['Destination.IP'] = df['Destination.IP'].apply(ip2int)

Thanks

**Comment by KH-RES** [comment]
thanks for your clarification.
I am totaly agree with you, all ip adresses needs to be converted into their coresponding numbers.
but if we go back to the generating error : the value **'172.19.1.46-10.200.7.7-52422-3128-6'** corresponds to the **Flow.ID** column. **so there is no traitement (no conversion) about this column.**

may be according to this, that error is occurred.

thanks

**Comment by krzysiekniburski** [comment]
Right, I did not mention this in code but in my research I did not use all of the features from dataset. There were few features that I removed (or rather did not use in the dataframe). Flow.ID does not give any value to the prediction because there is no data dependency so it should not be involved later in classification. You can also check for other features that will be pointless to use by checking unique values:
df.columns[df.nunique() <= 1]
and after that choose features that you want in your dataset:
feats = ['Source.IP','Source.Port',..., 'Idle.Max', 'Idle.Min']
X = df[feats]

**Comment by KH-RES** [comment]
now it becoms very clear.
thanks a lot.
